### ISSUE TITLE
这是啥问题

### ISSUE THREAD

**Issue by kami-king** [Diaosi1111/nonebot_plugin_lolmatch#2]
![Uploading Screenshot_2022-05-25-22-03-05-913_com.sonelli.juicessh.jpg…]()

**Comment by kami-king** [comment]
File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_lolmatch/__init__.py", line 12, in <module>
    from .data_source import LoLMatch
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_lolmatch/data_source.py", line 60, in <module>
    class LoLMatch:
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_lolmatch/data_source.py", line 329, in LoLMatch
    async def screenshot_for_after_match(cls, match_id: Union[str, int], match_round: int) -> list[io.BytesIO]:
TypeError: 'type' object is not subscriptable

**Comment by MaxCrazy1101** [comment]
额这个截图功能8太行，我也好久没改了，有点问题的，待我期末考完再来重构

**Comment by Area585** [comment]
> 额这个截图功能8太行，我也好久没改了，有点问题的，待我期末考完再来重构

**我也有这个错误，也是py3.8，催更hhh**

**Comment by MaxCrazy1101** [comment]
截图功能改了下，你可以再试试看

**Comment by Area585** [comment]
okkkk，今天下午抽空试了试，我在zhenxunBot上成功适配运行了hhh，谢谢作者大大。顺便我在这做个笔记，写下遇到的问题hhh

 **如图，插件报错ModuleNotFoundError: No module named 'sqlalchemy.engine.cursor'**
![image](https://user-images.githubusercontent.com/101381538/179271219-75c1a85f-c1a0-4976-95b5-f7f216d55656.png)
**问题描述：我使用的是zhenxunBot，系统为Ubuntu20.04LTS，在安装此插件时，出现了依赖版本冲突，导致导入插件报错**
**解决办法**：**实测安装databases0.4.3版本，以及SQLAlchemy1.3.24版本可以使插件正常运行**
（当然nonebot用户安装作者在pyproject.toml给出的版本就行）
**①`pip3 install -i https://mirrors.aliyun.com/pypi/simple flask-SQLAlchemy`
②`pip3 install -i https://mirrors.aliyun.com/pypi/simple --force-reinstall databases==0.4.3`
③`pip3 install -i https://mirrors.aliyun.com/pypi/simple --force-reinstall SQLAlchemy==1.3.24`**

**Comment by Area585** [comment]
作者大大，我还有一个问题，如下图：
![A(%XJIX2VKZ5%K2EPQ{_FRQ](https://user-images.githubusercontent.com/101381538/179273171-92879663-6e34-4300-a46f-73a540a762a3.png)

- 我想查看指定比赛的详情，随便试了一下，以为比赛ID就是图里插件“**lol赛事**”指令反馈的ID，结果不是，我看了一下**data_source**文件，**调用的是**[**scoregg**](https://www.scoregg.com)**的API**，那平常使用“**LOL详情** ”这一指令的话，就需要先去[**scoregg**](https://www.scoregg.com)查询比赛ID吗？
- 如果我理解错误的话，还请作者大大嘴下留情hhhh

**Comment by MaxCrazy1101** [comment]
这个比赛ID应该会在订阅之后每晚23点的简报里出现，联赛的id是用来订阅的。
datasource其实有两个函数，一个函数返回的信息是不带matchid的一个是带matchid的
接下来的更新计划就是优化这一部分的交互，计划是返回的信息会全部用更加直观的图片来代替。。。。。。。。

**Comment by Area585** [comment]
好的，了解了，插件正常工作，作者加油，期待作者大大的更新hhhh
![image](https://user-images.githubusercontent.com/101381538/179358416-aa7ba8af-e70e-4d83-88ac-94698a28afb3.png)
![1HI3I$H}72A QUEMBP2ZNM4](https://user-images.githubusercontent.com/101381538/179358446-b59d8fe2-5855-47aa-b040-094c5111f142.png)
