### ISSUE TITLE
关于template.py中代码报错

### ISSUE THREAD

**Issue by Hei-Qiang** [Diaosi1111/nonebot_plugin_lolmatch#3]
第472行代码报错
![1](https://user-images.githubusercontent.com/109337461/182740534-44d0dcb0-0440-4089-a138-b1d85d8510fb.png)
![2](https://user-images.githubusercontent.com/109337461/182740549-a0989786-acc0-445c-93d5-05eff7b28fdf.png)

**Comment by Hei-Qiang** [comment]
还有就是输入比赛id，他总是提示我输入数字
![image](https://user-images.githubusercontent.com/109337461/182741901-49f6ef98-2302-45a8-8840-8e05a125bb01.png)
![image](https://user-images.githubusercontent.com/109337461/182741918-ae65992a-3d0b-4283-96fc-910bcc6a45d4.png)

**Comment by Area585** [comment]
- 问题一：代码报错我也不太清楚，是不是因为查看代码缺少py编译环境(只是提一下，不太像hhhh)，**抑或者是数据格式不正确，输出字符str中包含换行符，未终止正则表达式，左、右"["括号的数量不正确**。这个让作者回答吧，不过我这边在服务器上倒是**正常运行**，没**发现**受到影响。
- 问题二：可能的原因，**你输入的比赛id虽然为数字，格式正确**，但是**实际中此数字ID不存在**，所以返回错误。如下图
![38S4@0M_EZ7T X2BK4OPMBJ](https://user-images.githubusercontent.com/101381538/184895592-d5226139-3418-4869-92ac-ae74b968ca88.png)

- **补充：**若想**订阅比赛**，可**依次**在**群里**给**bot**发送以下内容
**1. lol联赛**
**2. lol订阅 xxx**（其中**xxx**为你在**群聊**中发送"**lol联赛**"指令，bot返回的**联赛ID**，注意**命令与ID之间有空格**）
**3.** 一般情况下，**每日23点**(有时定时任务会偏差**1~2分钟**)，bot会反馈你订阅联赛的当日比赛结果

   **如下图：**
![TK~_J52J~Y6Z0L8~ JR`PWM](https://user-images.githubusercontent.com/101381538/185038204-fc1926ab-fee4-470c-9c46-f21441754d34.png)


- **补充：**使用**lol订阅 xxx**指令订阅联赛**之后**，若想测试bot是否能反馈，又不想等到23点，可以**在__init__.py文件**里修改定时任务部分。
**1.** **打开__init__.py文件**
**2.** **同时**按下**ctrl+f**，**输入并回车**搜索“**hour**”关键词(**代码第102行**)，**定位**到**注释**# **每日23点自动检查比赛的部分**
**3.** 把**hour**与**minute**修改为你想要的值，格式为**24小时制**，**jitter值可以不修改**
**4. 保存修改，重启bot**
   **如下图：**，修改后的意思为：每日**22点30分**自动检查比赛
![image](https://user-images.githubusercontent.com/101381538/184902449-587aa240-85fc-4b81-8669-ec86a8dbf649.png)

**Comment by Area585** [comment]
- 再次补充：订阅联赛之后，我不知道怎么取消订阅（好像代码中没有**取消订阅的命令**？我没细看hhh）。
- 目前我的**办法**就是：**删除插件目录下的数据库**，即**lol_match.db**这一文件（重启bot此文件会再次生成），这样所有群聊中的订阅记录都会清除。
- PS：订阅的群聊数量多的话就不太好操作，比如若只是**某个群聊想取消订阅**，那就进入**插件目录**下的**lol_match.db数据库**，**删除表或者表中的指定行**，不过我只有两个群聊订阅，把整个数据库删除倒也无伤大雅hhh。
![image](https://user-images.githubusercontent.com/101381538/184909826-af4ef5b9-2966-4be8-b4da-f2089161fd96.png)

**Comment by NealScx** [comment]
希望添加 **取消订阅** 的命令

**Comment by MaxCrazy1101** [comment]
> 希望添加 **取消订阅** 的命令

已添加 https://github.com/Diaosi1111/nonebot_plugin_lolmatch/commit/b0749e635ac046db8066d76b31d9e06c40979ff5
