### ISSUE TITLE
 cannot import name 'PluginMetadata' from 'nonebot.plugin' 

### ISSUE THREAD

**Issue by Qu1n-22** [Diaosi1111/nonebot_plugin_lolmatch#6]
这个我好像不能import，我是只能更新nonebot2么
![()E~6 @IL2G%IX%22YD1NCO](https://user-images.githubusercontent.com/58621926/191238413-39275d79-2e61-4abd-bdba-ba52f925e28d.png)

**Comment by MaxCrazy1101** [comment]
你可以尝试改一下源码把有关PluginMetadata的那一段删了试试

**Comment by Qu1n-22** [comment]
![image](https://user-images.githubusercontent.com/58621926/191424484-e4b8f3e9-5e6a-4b1f-827a-20148b7eaca3.png)
好像不行

**Comment by MaxCrazy1101** [comment]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/35657483/191480192-60171f84-1aea-4eda-bede-7a6de68fe8d5.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/35657483/191480434-8aa19205-9942-4bb9-bda7-6a58d0b6705c.png">
这几个地方改一下
