### ISSUE TITLE
nonebot中无法运行

### ISSUE THREAD

**Issue by showill** [Diaosi1111/nonebot_plugin_lolmatch#7]
nonebot正常运行的控制台：
![WZO@ E5M9FEPS4BO3AK 185](https://user-images.githubusercontent.com/89843618/198001924-e43e7783-b871-442c-8f1c-c5cedd2debf4.png)

在导入插件的时候运行就变成了：
![SE6%ZOH47``M}G_}RPMPRUY](https://user-images.githubusercontent.com/89843618/198001915-9ad4c550-64ce-4296-9f02-7178e31ed9df.png)

实在是不知道什么原因，球球大佬指点指点，使用其他插件可以正常使用

**Comment by showill** [comment]
是我导入的方法不对还是少了什么呢

**Comment by TFTree** [comment]
我成功运行了机器人，但是插件运行报错
![image](https://user-images.githubusercontent.com/83645868/198290070-754691f3-43c6-420e-ae24-7ff7c285f33a.png)

**Comment by dajiaofirst** [comment]
我的报错和上面的KeyError相同

**Comment by MaxCrazy1101** [comment]
更新了一下，可以试试看行不行 @OrphanFaker  @TFTree

**Comment by TFTree** [comment]
> 更新了一下，可以试试看行不行 @OrphanFaker @TFTree

可以运行了，但是出的图片中的文字都是方块，怀疑和编码方式有关，没有适配中文编码
<img width="346" alt="image" src="https://user-images.githubusercontent.com/83645868/205091667-588f6eb4-ed06-4866-8ce1-98fa9d9dedf7.png">

**Comment by TFTree** [comment]
@Diaosi1111  比赛详情查询出的图片中的中文也无法正常显示

![image](https://user-images.githubusercontent.com/83645868/205092762-17803dd4-e7e0-4645-83b4-f2d24586093a.png)

**Comment by MaxCrazy1101** [comment]
> @Diaosi1111 比赛详情查询出的图片中的中文也无法正常显示
> 
> ![image](https://user-images.githubusercontent.com/83645868/205092762-17803dd4-e7e0-4645-83b4-f2d24586093a.png)

运行在Linux上吗，你可以搜一下网页方块字的解决办法
可能可以参考https://www.cnblogs.com/EevilFish/p/12134717.html

**Comment by TFTree** [comment]
> > @Diaosi1111 比赛详情查询出的图片中的中文也无法正常显示
> > ![image](https://user-images.githubusercontent.com/83645868/205092762-17803dd4-e7e0-4645-83b4-f2d24586093a.png)
> 
> 运行在Linux上吗，你可以搜一下网页方块字的解决办法 可能可以参考https://www.cnblogs.com/EevilFish/p/12134717.html

在linux上安装了中文字体并且重启机器人以后已经显示正常了，不过现在api查询的貌似是世界杯比赛。
有个小建议就是使用说明能不能添加一下命令示例，感觉现在的不太清晰，我要尝试很多次才能试出正确的命令（目前我理解的是每个命令前面都要加lol关键字才行）0.0
好吧，我尝试了一下确实是如此，在每个命令前面加lol就行了，现在api查询世界杯的原因应该是目前只有世界杯联赛，不过可以查询往期lol的比赛
<img width="339" alt="image" src="https://user-images.githubusercontent.com/83645868/205111513-6dd9568b-8ed3-45f1-9c6d-0affb76bf98b.png">

<img width="328" alt="image" src="https://user-images.githubusercontent.com/83645868/205112573-80a869ca-5d2a-437e-b586-6b2514bf13c4.png">
